name: webrtcdemo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobx:
  flutter_mobx: 
  url_strategy:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  responsive_builder:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mobx_codegen: ^2.0.7
  build_runner: ^2.2.0
  flutter_gen:

flutter:
  uses-material-design: true